project:
  type: website

website:
  title: "ORDA for FAIR4RS"
  site-url: https://ns-rse.github.io/orda-slides
  description: "Using University of Sheffields figshare instance for improving FAIR4RS"
